name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
          architecture: x64

      - name: Install bundler and dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Check build
        run: bundle exec jekyll build
